### ISSUE TITLE
Bioscrape incorrectly manages parameter scope when loading SBML

### ISSUE THREAD

**Issue by WilliamIX** [ananswam/bioscrape#18]
UPDATE: Hunch is confirmed. The issue is that sbml has parameter names (which function within a scope) and parameter identifiers (which are more global). When bioscrape loads an SBML reaction, it indirectly creates a GeneralPropensity object with a rate formula that uses the sbml parameter names (typically). By default, these names might all be something like "k". Despite each "k" parameter having a different sbml identifier, when bioscrape parses the equation string it sees only the parameter name, not the identifier, and equates all parameters named "k" as the same.

Possible fixes:
The simplest fix is probably to alter the equation string to replace [rate_name] with [rate_name_parameter_id] or something like that. However, due to the general nature of these equations, we will have to be very careful about how we do this change. For instance, we wouldn't want to change a "k" inside of another parameter name like "k2".

The better fix might be to use the model API to do this, but that requires new API functionality. As stands, the model API requires all parameters to have names. I have been considering adding a way for parameters to be passed in with numeric values which are then automatically converted into dummy parameters inside of bioscrape. There is some subtlety here though because the param_dictionaries passed into propensity and delay objects are propensity/delay type specific. This means figuring out which parameters correspond to numerical quantities (and should become dummy variables) and which do not depends on the propensity/delay type. BioCRNpyler automatically takes care of this just by creating the dummy variables for the user - but it does this by having built in support for specific bioscrape types. In general, if we imagine adding more bioscrape types later on, it would be a pain to have to dramatically reprogram the model API to maintain new types. There should be some clever work around / abstraction but I'm not sure what it is.

**Comment by ayush9pandey** [comment]
- Yes, bioscrape imports all SBML reactions and gives "general" propensities to the reaction rate formula (even if the SBML reaction has a simple mass action kinetics). 
- SBML uses parameter identifiers in reaction rates not names.  In SBML, this is how you would set the rate to a reaction : 
```
reaction = model.createReaction()
# .....create reatants and products......
klaw = reaction.createKineticLaw()
formula = 'k1 * X - k2 * Y^2' # Refers to the species identifiers X and Y, and parameter identifiers k1 and k2 defined earlier (can be any general rate formula here)
klaw.setMath(libsbml.parseL3Formula(formula))
```

I didn't know about this bug in bioscrape that it looks at parameter names and not at ids, so definitely something that needs to be fixed there.

**Comment by WilliamIX** [comment]
Fixed in the lineage package very sloppily by rewriting SBML local variables with new names. At some point we need to make SBML load directly using the API.

**Comment by WilliamIX** [comment]
merged with master

**Comment by ayush9pandey** [comment]
reopening this issue as it is not fixed and doesn't work for SBML models that have multiple local parameters with same ids.

**Comment by WilliamIX** [comment]
This has been fixed by parameter renaming
